### ISSUE TITLE
GET with ampersand in parameters not working

### ISSUE THREAD

**Issue by tleekkul** [KayEss/fostgres#4]
GET request with ampersand in parameter is not working.

**Example**
**Request**
GET /snacks/M&M

**Response**
Status: 400 Bad Request
Body
```
Parsing error

Data: {
    "message" : "Expected a HTTP request",
    "value" : "GET /snacks/M&M HTTP/1.0"
}
```

I already tried to encodeURIComponent before GET request and I still get the same response (GET /snacks/M%26M)

**Comment by KayEss** [comment]
This is very strange. URLs with ampersands have worked forever on the web server, but they do need to be encoded.

Can you provide a full HTTP request and response for this?

**Comment by tleekkul** [comment]
Request
GET /cod/id/external/summary/ar/category/Matched/threepl/J&amp;T HTTP/1.1
Host: localhost:8080
Authorization: Bearer <JWT>
Content-Type: application/csj
Cache-Control: no-cache

Response
400 Bad Request
```
Parsing error

Data: {
    "message" : "Expected a HTTP request",
    "value" : "GET /id/external/summary/ar/category/Matched/threepl/J&T HTTP/1.0"
}
```

**Comment by KayEss** [comment]
It has to be escaped. I suppose that could be changed, but can you try 
with %26 in the request instead?

**Comment by KayEss** [comment]
Develop now contains a fix for the ampersand issue, but there is still a problem with unicode somewhere on the fostgres specific code path.
